accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name='index'),
    path('detail/<str:slug>', post_detail, name='detail'),
    path('create/', post_create, name='create'),
    path('update/<str:slug>', post_update, name='update'),
    path('delete/<str:slug>', post_delete, name='delete'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),

    path('api/post/', include('post.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home.html', {})

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Website Flutter</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'business-casual.min.css' %} " rel="stylesheet">

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Website Flutter</span>
      <span class="site-heading-lower">Business Casual</span>
    </h1>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home:home' %}">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'post:index' %}">Posts</a>
            </li>
            {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
              <li class="nav-item px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'post:create' %}">Add Post</a>
              </li>
              {% endif %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'accounts:login' %}">Log In</a>
            </li>
            {% endif %}
            <!--
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="">Contact</a>
            </li>
            -->
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0 small">Copyright &copy; Your Website 2021</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

    <!-- Script to highlight the active date in the hours list -->
    <script>
      $('.list-hours li').eq(new Date().getDay()).addClass('today');
    </script>

  </body>

</html>

templates/home.html
{% extends 'base.html'%}

{% block content %}

{% load static %}

  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'img/intro.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Fresh Coffee</span>
            <span class="section-heading-lower">Worth Drinking</span>
          </h2>
          <p class="mb-3">Every cup of our quality artisan coffee starts with locally sourced, hand picked ingredients. Once you try it, our coffee will be a blissful addition to your everyday morning routine - we guarantee it!
          </p>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Our Promise</span>
              <span class="section-heading-lower">To You</span>
            </h2>
            <p class="mb-0">When you walk into our shop to start your day, we are dedicated to providing you with friendly service, a welcoming atmosphere, and above all else, excellent products made with the highest quality ingredients. If you are not satisfied, please let us know and we will do whatever we can to make things right!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}